### ISSUE TITLE
setting up networking using this role

### ISSUE THREAD

**Issue by dimthe** [cyverse/openstack-ansible-host-prep#5]
Hello all
I have began learning openstack lately and i have been followng the openstack ansible role closely and i gave it a try. My goal is to build a multi node cloud using 5 or 6 vms .
Each VM has 4 network interfaces ( eth0 , eth1, eth2 and eth3 ) . I have been following the how to with success so far up to the point where i need to manually set up networking on these machines and i got lost :) this is where i got stuck
http://docs.openstack.org/developer/openstack-ansible/liberty/install-guide/targethosts-network.html

so i found this role  and my question now is this : Does this automatically sets up the necessary networking configs on each host ? 
if not , what do i have to edit .. ?

thanks

**Comment by c-mart** [comment]
@dimthe, thanks for getting in touch. 

To answer your question: yes, the [configure-networking](https://github.com/cyverse/openstack-ansible-host-prep/blob/master/ansible/roles/configure-networking/tasks/main.yml) role in this repo does set the base network configuration on each host that you need to get OSA working, but you do have to configure the hosts file and [group_vars](https://github.com/cyverse/openstack-ansible-host-prep/blob/master/ansible/inventory/group_vars/all), per the instructions in readme.md. Particularly, you need to specify the host IP address and names of the network interfaces in the `TARGET_HOSTS` dictionary. Here's an example from one of my deployments (hostnames and IPs changed slightly for this public post):
```
TARGET_HOSTS:
  openstack-01.example.org:
    ip: 10.1.1.1
    device1: enp130s0f0
    device2: enp130s0f1
  openstack-02.example.org:
    ip: 10.1.1.2
    device1: enp130s0f0
    device2: enp130s0f1
  openstack-03.example.org:
    ip: 10.1.1.3
    device1: enp130s0f0
    device2: enp130s0f1
```

Right now this code configures two network interfaces per host, but could easily be modified to support arbitrarily many interfaces.
